import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

# Load data
DATA_URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
@st.cache_data
def load_data(url):
    df = pd.read_csv(url)
    # Clean column names to snake_case
    df.columns = ["_".join("".join(c if c.isalnum() else " " for c in col).lower().split()) for col in df.columns]
    return df

df = load_data(DATA_URL)

# AutoML report (baseline)
AUTOML_REPORT = {
    "winner": "Random Forest",
    "primary_score": 1.0,
    "detailed_metrics": "Accuracy: 1.0",
    "tuning_status": "Baseline",
    "best_params": "Default",
    "verdict": "Perfect classification on the test set."
}

st.set_page_config(page_title="Iris Classification Dashboard", layout="wide")
st.title("Iris Classification Dashboard")

# Sidebar navigation
tabs = st.tabs(["Data Summary", "Correlation Matrix", "PCA Projection", "Model Performance", "Confusion Matrix", "Classification Report", "AutoML Report"])

# Tab 1: Data Summary
with tabs[0]:
    st.header("Data Summary")
    st.dataframe(df.head())
    st.write("Shape:", df.shape)
    st.write(df.describe())

# Tab 2: Correlation Matrix
with tabs[1]:
    st.header("Correlation Matrix")
    corr = df.corr()
    fig, ax = plt.subplots()
    sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax)
    st.pyplot(fig)

# Tab 3: PCA Projection
with tabs[2]:
    st.header("PCA Projection")
    from sklearn.decomposition import PCA
    pca = PCA(n_components=2)
    X = df.drop(columns=["species"])
    components = pca.fit_transform(X)
    pca_df = pd.DataFrame(data=components, columns=["PC1", "PC2"])
    pca_df["species"] = df["species"]
    fig2, ax2 = plt.subplots()
    sns.scatterplot(data=pca_df, x="PC1", y="PC2", hue="species", ax=ax2)
    st.pyplot(fig2)

# Tab 4: Model Performance (placeholder)
with tabs[3]:
    st.header("Model Performance")
    st.metric(label="Primary Score (Accuracy)", value=AUTOML_REPORT["primary_score"])
    st.write(AUTOML_REPORT["detailed_metrics"])
    st.write("**Winner Model:**", AUTOML_REPORT["winner"])
    st.write("**Tuning Status:**", AUTOML_REPORT["tuning_status"])
    st.write("**Best Params:**", AUTOML_REPORT["best_params"])
    st.success(AUTOML_REPORT["verdict"])

# Tab 5: Confusion Matrix
with tabs[4]:
    st.header("Confusion Matrix")
    from sklearn.model_selection import train_test_split
    from sklearn.ensemble import RandomForestClassifier
    X = df.drop(columns=["species"])
    y = df["species"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    cm = confusion_matrix(y_test, preds, labels=model.classes_)
    fig3, ax3 = plt.subplots()
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=model.classes_, yticklabels=model.classes_, ax=ax3)
    ax3.set_xlabel("Predicted")
    ax3.set_ylabel("Actual")
    st.pyplot(fig3)

# Tab 6: Classification Report
with tabs[5]:
    st.header("Classification Report")
    report = classification_report(y_test, preds, output_dict=True)
    st.write(pd.DataFrame(report).transpose())

# Tab 7: AutoML Report
with tabs[6]:
    st.header("AutoML Report")
    st.subheader("Leaderboard")
    leaderboard = pd.DataFrame([
        {"Model": "Random Forest", "Score": 1.0},
        {"Model": "Gradient Boosting", "Score": 1.0},
        {"Model": "Logistic Regression", "Score": 1.0}
    ])
    st.table(leaderboard)
    st.subheader("Metrics")
    st.metric(label="Primary Score", value=AUTOML_REPORT["primary_score"])
    st.write(AUTOML_REPORT["detailed_metrics"])
    st.subheader("Details")
    st.json(AUTOML_REPORT)

# Footer
st.caption("Dashboard generated by BlazeWatson – AutoML pipeline")
