import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Page config
st.set_page_config(layout="wide")

# Load data
DATA_URL = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
@st.cache_data
def load_data(url):
    df = pd.read_csv(url)
    # Safe snake_case cleaning
    df.columns = ["_".join("".join(c if c.isalnum() else " " for c in col).lower().split()) for col in df.columns]
    return df

df = load_data(DATA_URL)

# Dynamic column groups
num_cols = df.select_dtypes(include=np.number).columns.tolist()
cat_cols = df.select_dtypes(include='object').columns.tolist()

st.title("Universal Data Dashboard")

# Tabs
tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs(["📋 Profiling", "🛠️ Feature Engineering", "📊 Distributions", "🔗 Correlations", "🧬 PCA", "🧩 Clustering", "🤖 AutoML"])

with tab1:
    st.header("Data Profiling")
    st.subheader("Head of dataset")
    st.dataframe(df.head())
    st.subheader("Summary statistics")
    st.dataframe(df.describe())
    st.subheader("Missing values")
    missing = df.isnull().sum()
    st.dataframe(missing[missing>0])

with tab2:
    st.header("Feature Engineering")
    if num_cols:
        col = st.selectbox("Choose Column to Transform", num_cols)
        fig = px.histogram(df, x=col, nbins=30, title=f"Histogram of {col}")
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.write("No numeric columns available for transformation.")

with tab3:
    st.header("Distributions (Violin Plots)")
    if num_cols:
        cols_to_show = num_cols[:6]
        for c in cols_to_show:
            fig = px.violin(df, y=c, box=True, points="all", title=f"Violin plot of {c}")
            st.plotly_chart(fig, use_container_width=True)
    else:
        st.write("No numeric columns to display.")

with tab4:
    st.header("Correlation Heatmap")
    if len(num_cols) > 1:
        corr = df[num_cols].corr()
        fig = go.Figure(data=go.Heatmap(z=corr.values, x=corr.columns, y=corr.index, colorscale='Viridis'))
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.write("Not enough numeric columns for correlation heatmap.")

with tab5:
    st.header("PCA Scatter")
    if len(num_cols) > 1:
        scaler = StandardScaler()
        scaled = scaler.fit_transform(df[num_cols])
        pca = PCA(n_components=2)
        components = pca.fit_transform(scaled)
        pca_df = pd.DataFrame(components, columns=["PC1", "PC2"])
        fig = px.scatter(pca_df, x="PC1", y="PC2", title="PCA 2D Scatter")
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.write("Insufficient numeric columns for PCA.")

with tab6:
    st.header("K-Means Clustering")
    if len(num_cols) > 1:
        k = st.slider("Select number of clusters", 2, 10, 3)
        scaler = StandardScaler()
        scaled = scaler.fit_transform(df[num_cols])
        kmeans = KMeans(n_clusters=k, random_state=42)
        clusters = kmeans.fit_predict(scaled)
        df_cluster = df.copy()
        df_cluster["cluster"] = clusters
        fig = px.scatter_matrix(df_cluster, dimensions=num_cols[:5], color="cluster", title="Cluster Scatter Matrix")
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.write("Not enough numeric columns for clustering.")

with tab7:
    st.header("AutoML Tournament")
    target = st.selectbox("Select Target", df.columns)
    if st.button("Run AutoML"):
        with st.spinner("Running AutoML tournament..."):
            # Simple wrapper calling the backend AutoML function
            import json, requests
            payload = {
                "dataset_url": DATA_URL,
                "target_column": target,
                "task_type": "regression" if np.issubdtype(df[target].dtype, np.number) else "classification",
                "tune_hyperparameters": False
            }
            # Assume existence of an endpoint; placeholder response
            st.success(f"AutoML completed. (Mock) Best model: Ridge Regression with score {0.1627:.4f}")
            st.json({"best_model": "Ridge Regression", "score": 0.1627})

st.caption("Generated by BlazeWatson – universal dashboard template.")
